### ISSUE TITLE
BLAST Wrapper

### ISSUE THREAD

**Issue by dbolotin** [milaboratory/milib#8]
BLAST Wrapper.
As processor (Sequence -> alignment)

**Comment by PoslavskySV** [comment]
BLAST does not support normal piping: one have to run `blastx` process for each query.

**Comment by dbolotin** [comment]
BATCH_SIZE environment variable solves it!

See: http://www.ncbi.nlm.nih.gov/IEB/ToolBox/CPP_DOC/lxr/source/src/algo/blast/blastinput/blast_input_aux.cpp#L82
